### PR TITLE
Updated HACS Installation instructions

### PR DESCRIPTION
**Pull request by eugeneniemand**
This was my first custom lovelace card I added and I did not know about the need for www folder. I would have thought HACS would add it but the installation succeeded but did nothing. Even after a restart it was showing in HACS but did not exist on disk.

Ok still struggled next I found out I need to register the resources, you sort of mention in the manual setup  and the hacs popup it but again not clear. I cant see a hacsfiles folder but it did create the www/community/scheduler-card files. I doubt I have the information 100% correct here but at least it seems to be working now

### CODE REVIEW

**Comment by nielsfaber** [comment]
Great stuff!
Actually I’m not a HACS user myself. All that’s written there is contributed by others.
Your instructions seem a good improvement, thanks!

**Comment by nielsfaber** [comment]
PS: not to be greedy, but maybe the scheduler-component should be updated as well.
Most people struggle with that one.
Since you recently went through the steps, could you check if the instructions are accurate?

**Comment by KTibow** [comment]
I don't like this. HACS has always auto-added the resource. Maybe add "If HACS says resource not loaded, manually add it with these steps:"
I really don't think that the first part needs to be there either, maybe put it in a separate section?

**Comment by eugeneniemand** [comment]
@KTibow Happy to change it, to be honest I still dont have it working. The card shows but no entities are appearing
image
Still trying to figure it out. As soon as I have it working I'm happy to update the docs on both again

**Comment by nielsfaber** [comment]
You need to define which entities you want to use with scheduler.
You can do this via the card editor UI or with YAML (`include` setting)

**Pull request merged**
