### PR TITLE
Fix prettier config format

### PR DESCRIPTION
**Pull request by JSteunou**
The config file was in the wrong format.

Be careful, once this is merged, eslint will work again and you have a lot of lint error in  your source code.

Use VSCode with auto-format to help you with ;)

And please add EOF newline + remove EOL blank / space (this is pretty standard)

### CODE REVIEW

**Comment by nielsfaber** [comment]
Cool! Can I hire you?
I already gave up on linting, since I couldn't get it to work.
WIll give it a second try, thanks

**Comment by JSteunou** [comment]
I'm *Gromy* on the HA community. I'm a JS coach & dev. I have little time, but I can help you. That the least I can do given what you are doing for all of us using your plugin ;)

**Comment by JSteunou** [comment]
I checked the boilerplate card, they fix this issue by renaming the file to .prettierrc.js instead of converting it to json. Both fix are valid. https://prettier.io/docs/en/configuration.html

JSON is simpler, JavaScript format is used when you wanna extends from another config file.

**Comment by KTibow** [comment]
If you completely remove it, it will only check for syntax errors.

**Comment by JSteunou** [comment]
I would not advice to remove it. Having a prettier + eslint + vscode autoformat + CI to lint is a bare standard minimum on a JS collaborative project.

**Comment by KTibow** [comment]
@JSteunou sorry, confused ESLint with Prettier.

**Pull request merged**
