### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by KTibow**
This validates code with ESLint.

### CODE REVIEW

**Comment by nielsfaber** [comment]
Thanks for the effort, but i don't think this is useful for me.
I think it would be better to run the linter before committing.
Also the eslint config you made doesn't work for this repo, since it is 99% typescript.

**Comment by KTibow** [comment]
What do you mean about the typescript part? It can help catch invalid JS, and later is better than not at all..

**Comment by nielsfaber** [comment]
This card is not in javascript...

**Comment by KTibow** [comment]
sorry. I didn't see that the action didn't work with TS.

**Pull request closed without merging**
