### PR TITLE
Workflow improvements

### PR DESCRIPTION
**Pull request by KTibow**
Tries to load all languages, and checks for completeness. Also switches to the new HACS action.

### CODE REVIEW

**Comment by KTibow** [comment]
@nielsfaber finally finished.

**Comment by nielsfaber** [comment]
This thing looks amazing!
Can’t wait to see it in action, the translation files seem to be all different.
Would it show what’s wrong or missing when someone creates a PR with an updated language file?
Or do I need to run some command to get a list of inconsistencies?

ps: I couldn’t figure out what’s with the locale stuff. What does it check for?
 I would be happy if missing items give an error, so people can make adjustments.
Would be also fine with me if the English translations are copy-pasted to those lines, I think that’s what HA does currently.

**Comment by KTibow** [comment]
> Would it show what’s wrong or missing when someone creates a PR with an updated language file?

It looks for JSON errors, and it prints out missing items for all languages.

> Or do I need to run some command to get a list of inconsistencies?

It runs on push, and also under the checks section:
image
image

> I couldn’t figure out what’s with the locale stuff. What does it check for?

Could you clarify?

> I would be happy if missing items give an error, so people can make adjustments.
Would be also fine with me if the English translations are copy-pasted to those lines, I think that’s what HA does currently.

So you mean copy the english versions in, and throw an exception for a non-existent item?

**Comment by nielsfaber** [comment]
> > Would it show what’s wrong or missing when someone creates a PR with an updated language file?
> 
> It looks for JSON errors, and it prints out missing items for all languages.
> 
> > Or do I need to run some command to get a list of inconsistencies?
> 
> It runs on push, and also under the checks section:
> image
> image
> 
> > I couldn’t figure out what’s with the locale stuff. What does it check for?
> 
> Could you clarify?
> 
Never mind my comment. I was curious about the use of the `Locale` class. 
But it seems for printing messages with readable info regarding the language involved.

> > I would be happy if missing items give an error, so people can make adjustments.
> > Would be also fine with me if the English translations are copy-pasted to those lines, I think that’s what HA does currently.
> 
> So you mean copy the english versions in, and throw an exception for a non-existent item?

When users create a translation, they take the English file as baseline and translate all to their language.
So if I make changes to the English file (later on), it would be great if the other translations could be 'synced' such that the added (or removed) lines from the English file were automatically inserted (or removed) in the local files.
This is not really related to validation though, it is just to keep the files in sync. 
Should maybe be a separate action, or I need to find a better way-of-working myself.

Thanks a lot for your contribution with this script! 
Let's see what will happen..

**Pull request merged**
