### PR TITLE
Fix #213 - Increase Sun maxOffset

### LINKED ISSUE #213: Feature Request: Allow Greater Offset for Sun & More Exact Times
There shouldn't be only a two hour limit for sunrise and sunset offsets. Potentially remove the limit all together or make it larger, say 12 hours in either direction?

Another suggestion: Increase the precision of the time to be at a minute level instead of being on tens.

### PR DESCRIPTION
**Pull request by dj4ngo**

### CODE REVIEW

**Comment by nielsfaber** [comment]
I dont like it. Programming something for 12 hours before sunset does not make sense at all (it would be almost sunrise even).
Your change also may result in a time that is after midnight (so a day later), this is dangerous.

**Comment by dj4ngo** [comment]
Indeed, I tested it with 12 hours and the comportment was ok to go from a day to an other one.

No problem to close it, in fact, I do not use it. ;) 
It was more about begin to understand the code and set-up my environment. Since I did it, I proposed it to save you some time if it was good for you. 

Thx.

**Comment by nielsfaber** [comment]
Ah ok!
It's important to keep thinking of the impact of every change.
Most parts of the code have a story behind them.
Unfortunately (for you) there is not much comment in the code, most context is in my head.

PS: I hate rejecting PRs.. Don't want to throw away anyone's efforts. But I have quite a strong mind/vision about the card, would like to keep it minimalistic/user-friendly as much as possible.

**Comment by dj4ngo** [comment]
Ah ah; no problem !
I know quite well open-source world, I am working in an open-source company  ;) 

Rejecting a bad PR is a good point for the product maturity and stability, you've made the right choice. Don't worry.

On an other hand, I think 2 hours can be a bit small, but I have no example in mind. If one day I have the need, I'll open a new issue to discuss it with arguments ;)

**Pull request closed without merging**
