### PR TITLE
Update it.json

### PR DESCRIPTION
**Pull request by devil8ball**
Update to match the new schema.
Regarding the "days_range" value, the correct translation should verify these two conditions:

{if {startDay} is domenica} dalla {else} dal
{if endDay is domenica} alla {else} al

...but i don't know how to implement a multiple condition on json -.-'

### CODE REVIEW

**Comment by nielsfaber** [comment]
How did you do that so quickly!! 😮 😮

**Comment by devil8ball** [comment]
> How did you do that so quickly!! 😮 😮

Secret power of "Nothing to do" ;)

**Comment by nielsfaber** [comment]
> {if {startDay} is domenica} dalla {else} dal
{if endDay is domenica} alla {else} al
...but i don't know how to implement a multiple condition on json -.-'

The truth is that these 'templates' are just a little creation of my own, so it could alway be extended to support this use-case.
I will see what I can do. I will make the changes myself if i got something working.

**Comment by devil8ball** [comment]
> The truth is that these 'templates' are just a little creation of my own, so it could alway be extended to support this use-case.
> I will see what I can do. I will make the changes myself if i got something working.

I'm honest, this is just a "very" nice to have, the value "da {startDay} a {endDay}" is grammatically correct in every day condition.

**Pull request merged**
