### PR TITLE
Use ha-blueprint

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041?u=ktibow
This makes CI use it.

### CODE REVIEW

**Comment by KTibow** [comment]
Still waiting for GH actions to pull the updated code.

**Comment by nielsfaber** [comment]
I think we discussed this already.
I would rather run such checks locally, to prevent that code is modified after pushing (gives me quite some headaches)..

**Comment by KTibow** [comment]
Got it. Just wondering, any reason you're fine with commit amending for black and isort (Python) but not prettier (JS)?

**Comment by nielsfaber** [comment]
The main reason is that the card is updated much more often. I also have a bit more experience in JS/TS than python, so I make less errors. 
It’s not that I don’t appreciate your efforts, the thing is that I don’t really understand how these things work and how I should avoid merge conflicts and stuff. So I am a bit old-fashioned I guess.

**Comment by KTibow** [comment]
Fair point. Lint != formatter, you can [disable the formatter](https://github.com/KTibow/ha-blueprint/blob/main/README.md#some-notes) if you want. Ideally you don't need to worry about the workflow, you just go around development as usual.

**Pull request closed without merging**
