### PR TITLE
new french translation

### PR DESCRIPTION
**Pull request by claudegel**

### CODE REVIEW

**Comment by claudegel** [comment]
I've made the translation directly into my master instead of creating a branch. I hope it can be merged as is

**Comment by KTibow** [comment]
Of course, it doesn't matter, but ideally you would create a new PR so there's 1 commit instead of 4

**Comment by claudegel** [comment]
Next time I'll create a branch for a cleaner PR. Can you merge that one or is it better that I cancel it and create a new one

**Comment by nielsfaber** [comment]
Thanks!

**Pull request merged**
