### PR TITLE
italian language improvement

### PR DESCRIPTION
**Pull request by MaurizioScala**
italian language improvement

### CODE REVIEW

**Comment by pattarom** [comment]
May suggest these other changes?
line 8: "cancella" -> "elimina"
line 40 to 46: weekdays in italian must written in lowercase without capital letters
line 92: "aspirapolveri" -> "aspirapolvere"
line 114: "all' {sunEvent}" -> "al{sunEvent}"
line 115: "alba" -> "l' alba"
line 116: "tramonto" -> " tramonto"
line 119: "1 altro task" -> "un altro task"

**Comment by MaurizioScala** [comment]
Yes, I agree, please make the changes and open a pull request

**Comment by nielsfaber** [comment]
There is an unfortunate situation, seems that someone else took the initiative to update the translation, around the same time as you did.
See: https://github.com/nielsfaber/scheduler-card/pull/145

I would propose to you to review his PR and then I will merge that one.
His PR was created (a bit) before yours, so it seems the most fair to me.
Funny because a week ago, there was no italian translation at all, now everyone seems eager to help.

**Comment by nielsfaber** [comment]
i will merge by hand.

**Pull request closed without merging**
