### PR TITLE
Fixing a bug in saving fractional values

### PR DESCRIPTION
**Pull request by mjsambol**
Per conversation with Niels. I've tested this locally, confirm that fractional changes are saved and persist across restarts of HA.

### CODE REVIEW

**Comment by nielsfaber** [comment]
Excellent, thanks for helping out!

**Comment by mjsambol** [comment]
Niels, I just found that I am not able to add conditions to existing or new schedules. I don't think this is related to the PR I submitted, but it is relatively new, because many of my existing schedules do use conditions. Now when I try to add a condition, the "save" button is never enabled. I debugged far enough to find that the condition for the save button is 

disabled=${!this.selectedEntity||!this.conditionMatchType||!this.conditionValue}

and while this.selectedEntity and this.conditionMatchType are updated when I select them, this.conditionValue is never updated.

I am not able to find when this was corrupted in the code.

I tried replacing my patched code with the version from HACS, but it seems I'm not doing it right as I still get the fix for fractional values along with the bug in setting conditions. I suggest you test it in your own build.

**Comment by mjsambol** [comment]
I think the source of this issue may be in [this commit](https://github.com/nielsfaber/scheduler-card/commit/8b4767e5149832251f72e5b364b95a723d8b02fc#diff-805e3cc26169b859e5c3bb7683facf1d7e075d8a0c7da637610783c1380ab401)

I tried to test rolling back that change, but am again unable to build, getting the error:

```
rollup v1.32.1
bundles src/scheduler-card.ts → dist...
[!] (plugin rpt2) Error: /home/moshe/git/scheduler-card/src/helpers.ts(3,10): semantic error TS2305: Module '"../node_modules/custom-card-helpers/dist"' has no exported member 'FrontendTranslationData'.
src/helpers.ts
Error: /home/moshe/git/scheduler-card/src/helpers.ts(3,10): semantic error TS2305: Module '"../node_modules/custom-card-helpers/dist"' has no exported member 'FrontendTranslationData'.
    at error (/home/moshe/git/scheduler-card/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at throwPluginError (/home/moshe/git/scheduler-card/node_modules/rollup/dist/shared/node-entry.js:11878:12)
    at Object.error (/home/moshe/git/scheduler-card/node_modules/rollup/dist/shared/node-entry.js:12912:24)
    at Object.error (/home/moshe/git/scheduler-card/node_modules/rollup/dist/shared/node-entry.js:12081:38)
    at RollupContext.error (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at lodash_3 (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11)
    at arrayEach (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at _.each (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9342:14)
    at printDiagnostics (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/moshe/git/scheduler-card/node_modules/rollup-plugin-typescript2/src/index.ts:234:5)
```

**Comment by mjsambol** [comment]
Sorry for all the noise here... while testing last night I hadn't been refreshing my browser cache. Once I did that, I verified that if I roll back to the version installed by HACS I lose the fix for fractional temperatures but regain the ability to set and edit conditions.

The only change that looks suspicious to me is [this one](https://github.com/nielsfaber/scheduler-card/commit/8b4767e5149832251f72e5b364b95a723d8b02fc#diff-805e3cc26169b859e5c3bb7683facf1d7e075d8a0c7da637610783c1380ab401), but as that's tagged 2.1.4, it should be in the build I'm getting from HACS. Which leaves me to fear that my fractional temp fix is causing this regression with conditions.

Can you please help me get past the build problem so that I can try to dig into this?

**Comment by mjsambol** [comment]
I got past my build errors and have fixed the problem in the options card. The fix in this PR either caused or exposed a problem which requires the patch below.

**However**, this patch can't be applied to the current head, because other changes have broken the options card in head such that the list of availableMatchTypes is no longer populated. I don't understand those changes well enough to fix them. 


```
diff --git a/src/views/scheduler-options-card.ts b/src/views/scheduler-options-card.ts
index b429dd0..5ddfc1f 100755
--- a/src/views/scheduler-options-card.ts
+++ b/src/views/scheduler-options-card.ts
@@ -4,7 +4,7 @@ import { localize } from '../localize/localize';
 //import { Config } from '../config';
 import { EConditionType, CardConfig, EntityElement, Condition, EConditionMatchType, ScheduleConfig, ListVariableOption, Dictionary, ERepeatType, Timeslot, EVariableType, ListVariable, LevelVariable, Group } from '../types';
 
-import { HomeAssistant } from 'custom-card-helpers';
+import { HomeAssistant, fireEvent } from 'custom-card-helpers';^M
 import { entityGroups } from '../data/entity_group';
 import { commonStyle } from '../styles';
 import { parseEntity } from '../data/entities/parse_entity';
@@ -264,7 +264,7 @@ export class SchedulerOptionsCard extends LitElement {
       <scheduler-variable-picker
         .variable=${states}
         .value=${this.conditionValue}
-        @value-changed=${(ev: CustomEvent) => this.conditionValue = ev.detail.value}}
+        @value-changed=${(ev: CustomEvent) => {this.conditionValue = ev.detail.value; fireEvent(this, 'value-changed', { value: this.conditionValue });}}^M
       >
       </scheduler-variable-picker> 
       `;
```

**Comment by menocode** [comment]
Is this fix in the latest release on HACS or do I need to install the fix manually (no clue how to do that). 
I tried existing schedules and built new ones and still have the round up problem.

**Comment by nielsfaber** [comment]
Just a little bit more patience is enough, I am working towards a release.

**Comment by menocode** [comment]
Niels -most appreciate. Love this hack- my house runs on it. A lifesaver for me.

**Pull request merged**
