### PR TITLE
Commit lock file

### PR DESCRIPTION
**Pull request by SuperSandro2000**
I am currently packaging this for NixOS and we require node projects to have a lockfile and this ensures that people know from which dependency versions the files in the dist directory where created from.

### CODE REVIEW

**Comment by gatisr** [comment]
I've reviewed the changes in this PR and noticed that the package.lock.json file has been updated. I encountered a similar issue in the past with version mismatches. During local builds, I faced Babel error in post-build. It only worked smoothly when using Rollup).

I wanted to test the newly added language, but after build without lockfile, the language didn't seem to be fully applied.

While this PR looks promising, I believe it would be safer for the owner to double-check and ensure everything is set up correctly.

**Comment by nielsfaber** [comment]
I don't think the package lock file should be added to this project.
This is a file that is part of a local installation, along with the installed files in the node_modules folder.
If specific versions of packages are required, this should be indicated in the package.json instead.

**Comment by gatisr** [comment]
I understand your point about keeping the project lightweight and avoiding unnecessary clutter. However, I'd like to present argument in favor of including the package.lock.json file in this repository.

As mentioned in the documentation from npm, the package.lock.json file serves as a crucial tool for ensuring consistency in the dependencies across different environments and installations. It helps to mitigate potential issues stemming from version discrepancies that may arise due to factors such as different npm versions or installation algorithms. By including the package.lock.json file in this repository, we can ensure that anyone who clones or forks this project will have a consistent and reproducible build environment.

I strongly believe that including the package.lock.json file in this repository would be beneficial for the long-term maintainability and reliability of this project. It provides a clear and consistent dependency management strategy, aligning with best practices recommended by npm. Also it helps to prevent unexpected behavior and ensures that project builds are not susceptible to "works on my machine" issues.

https://docs.npmjs.com/cli/v6/configuring-npm/package-locks#using-locked-packages

**Comment by SuperSandro2000** [comment]
If I generate the lock file for nixpkgs, then it will very likely contain different content then the one you used local and debugging issues which might be rooted in this, can be a big waste of time for everyone.

**Pull request closed without merging**
