### PR TITLE
et-EE translation

### PR DESCRIPTION
**Pull request by Repsionu**
Some humble translation to Estonian :-)
[Scheduler-et-EE.txt](https://github.com/nielsfaber/scheduler-card/files/5263364/Scheduler-et-EE.txt)

### CODE REVIEW

**Comment by Repsionu** [comment]
Some checks were not successful? How can I improve this?

**Comment by nielsfaber** [comment]
Could you please make a PR from master branch?
Your PR has a lot of extra changes because you used one of my WIP branches.

**Comment by nielsfaber** [comment]
Don't mind the check failures, there is a HACS compatibility checker that currently fails for all commits.

**Comment by nielsfaber** [comment]
Ah sorry, didn't see that you made a text file with your translation.
Very creative 😉 
I will add it in the next release, you can check the result yourself.
Thanks!

**Comment by Repsionu** [comment]
Thanks :-)

**Pull request closed without merging**
