### PR TITLE
feat: increment up to 24 entries in daily schedule

### PR DESCRIPTION
**Pull request by override80**
Hope this makes sense. With this change, we could be allowed to create hourly schedules for a whole day. E.g. I can run a pool pump every 3 hours for an hour from midnight.

### CODE REVIEW

**Comment by nielsfaber** [comment]
I only added this limit due to limited space/width in the card (for the same reason the timestep is fixed to 15 mins).
Think it will look really nasty with 24 timeslots..

If you have any idea how to fix this, you're the man!

Apart from that I'm fine with it (and it should work, there are no limits anywhere else).

Did you think of creating just the 8 timeslots, and triggering a script in each timeslot, which turns the pump ON, and OFF an hour later?

**Comment by override80** [comment]
Well it does not look so bad in the end... I would only reduce font and balloon size to accomodate short timeframes better in the UI... Otherwise, well, if you are crazy as I am and add lots of timeframes you can expect a weird result :smile: 

image

**Comment by nielsfaber** [comment]
You are clearly cheating 😄 
This card is made for standard Lovelace column layout and mobile devices.

The font size is not really open for debate, my 60 year old mom is a target user (seriously)

At some point I would like to make some balloon-collision-dodging algorithm, and color timeslots based on the action.
I guess the 'urn o' would also look nicer if splitted in 2 lines (or just say ON).

**Comment by Misiu** [comment]
@nielsfaber I have an idea for optimizing the view. I saw a similar view in a desktop app I used some time ago (can't remember the name, I'll try to find it).
Currently, the timeline view is displaying all the slots, all tooltips, and all drag handlers (round buttons with arrows).
If we have more timeslots the tooltips overlap (as we can see on the @override80 screenshot).
The idea is to initially display the timeline without the tooltips and the drag handlers, but with vertical lines as separators, then when you click (or press) on the slot you will see the tooltips and the drag handlers, but only for the currently selected slot.
A similar idea is implemented in Bryntum's Scheduler component (https://www.bryntum.com/examples/scheduler/basic/).

I can create a new issue for that if I get your initial approval.

**Comment by nielsfaber** [comment]
> when you click (or press) on the slot you will see the tooltips and the drag handlers, but only for the currently selected slot.

This doesn't really solve anything since the problem already occurs with the markers of the begin+end time of a single slot.

My original plan was to make a GUI like Tado has: https://community.home-assistant.io/t/scheduler-card-custom-component/217458/24?u=neliss

This GUI (I have it on my phone) has the function that when you click on a timeslot, there is a zoom-in animation and you only see the extend of the selected timeslot (+ a bit extra so you see what comes before and after).
This is what I really want to make still, but I didn't find the time to get to it.

**Comment by Misiu** [comment]
> This doesn't really solve anything since the problem already occurs with the markers of the begin+end time of a single slot.

I agree, but this will remove extra tooltips that aren't needed and will make the view clearer.
This is just a short term solution, a zoom-like solution would be better.
Maybe you can add "smart" tooltips, something like this:
image
Idea is to have tooltips default as it, but they should move to the left or right to not overlap each other.
With multiple tooltips, this won't help, but with two this will make a difference.

**Comment by nielsfaber** [comment]
I didn't consider that. Would be indeed a quick-win fix. 
Let's go for it!

**Comment by Misiu** [comment]
I've created the above picture in an image editor, just to visually show what I mean.
Do you want me to create a new issue for this? I'm not a native English speaker, so maybe you will describe it better than me 🙂

**Comment by nielsfaber** [comment]
Nie ma problemu, wiem ...

Please open a feature-request for your idea + the picture.
No need for a story.
Maybe we can discuss a bit more about when the balloons should pop up and when they should hide.

Its good to have a thread to discuss the progress and maybe ideas of others..

**Pull request merged**
